### ISSUE TITLE
build trouble on Fedora28

### ISSUE THREAD

**Issue by newville** [caqtdm/caqtdm#40]
I'm trying to build caQtDM on Fedora 28 with Qt5.1.   After getting all the devel packages installed and configuring caQtDM_Env, I've run into some problems that I think will require changing the build scripts, or perhaps something more drastic...

##  Issue 1:  rpc no longer included with glibc

It seems that in order to improve IPv6 compatability, glibc 2.27 no longer comes with Sun's RPC libraries by default.  I do not know if this is Fedora/RH specific or applies to all of glibc.   The rpc/ and xdr header files and libraries can be installed from the "libtirpc" library.

That means that `-I/usr/include/tirpc` needs to be included in the `INCPATH` directive of `caQtDM_QtControls/Makefile`, and that `-ltirpc` needs to be added to the `LIBS` directive of `caQtDM_Viewer/Makefile`.

I did not track down far enough to see where these originate.   

## Issue 2:  Qt5X11Extras is required

The devel package for Qt5X11Extras needs to be installed, and the `caQtDM_Viewer/Makefile` needs to be altered to have

`INCPATH = ....  -I/usr/include/qt5/QtX11Extras`

and 

`LIBS = -LQt5X11Extras`

## Issue 3:  immediate coredump, no messages

Unfortunately, although those changes allow it to be build, caQtDM gives an immediate core dump.

**Comment by AntonMezger** [comment]
I will follow that up after the epics collaboration meeting

Best regards

Anton

Envoyé de mon iPhone

Le 6 juin 2018 à 14:26, Matt Newville <notifications@github.com<mailto:notifications@github.com>> a écrit :


I'm trying to build caQtDM on Fedora 28 with Qt5.1. After getting all the devel packages installed and configuring caQtDM_Env, I've run into some problems that I think will require changing the build scripts, or perhaps something more drastic...

Issue 1: rpc no longer included with glibc

It seems that in order to improve IPv6 compatability, glibc 2.27 no longer comes with Sun's RPC libraries by default. I do not know if this is Fedora/RH specific or applies to all of glibc. The rpc/ and xdr header files and libraries can be installed from the "libtirpc" library.

That means that -I/usr/include/tirpc needs to be included in the INCPATH directive of caQtDM_QtControls/Makefile, and that -ltirpc needs to be added to the LIBS directive of caQtDM_Viewer/Makefile.

I did not track down far enough to see where these originate.

Issue 2: Qt5X11Extras is required

The devel package for Qt5X11Extras needs to be installed, and the caQtDM_Viewer/Makefile needs to be altered to have

INCPATH = .... -I/usr/include/qt5/QtX11Extras

and

LIBS = -LQt5X11Extras

Issue 3: immediate coredump, no messages

Unfortunately, although those changes allow it to be build, caQtDM gives an immediate core dump.

**Comment by newville** [comment]
@AntonMezger Great! Thanks!

**Comment by HelgeBrands** [comment]
Hi Matt,

the „problem“ with rpc is already solved. For Windows/Mac/Mobile this did never exists.  To solve this you can modify in qtdef.pri :

# for some architectures this has to be defined for scan2D
macx | win32 | ios | android {
DEFINES += XDR_HACK
DEFINES += XDR_LE
CONFIG += XDR_HACK
}

You can add “unix” or remove the brackets completely.
I think the best way is to remove this RPC dependency, but I have to discuss this with Anton.

Best regards
                Helge

**Comment by newville** [comment]
@HelgeBrands  Ah, thanks for that.  Indeed, adding `unix | ` to `caQtDM_Viewer/qtdefs.pri` does seem to solve the rpc problem. 

I still have to add Qt5X11Extras to build the Viewer, and still get an immediate crash running caQtDM.

**Comment by newville** [comment]
I was using 3.15-5 as well, but will retry with 3.16.1.     

How would I configure caQtDM_Env to use Qt4?

**Comment by HelgeBrands** [comment]
Hi Matt,

you have to use the right qmake for Qt4. The build script is using qmake, but on Linux systems with 2 Qt versions you have qmake-qt4 and qmake-qt5. So you can change it with an symbolic link.

Best regards
                Helge

Von: Matt Newville [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. Juni 2018 18:32
An: caqtdm/caqtdm
Cc: Brands Helge (PSI); Mention
Betreff: Re: [caqtdm/caqtdm] build trouble on Fedora28 (#40)


I was using 3.15-5 as well, but will retry with 3.16.1.

How would I configure caQtDM_Env to use Qt4?

**Comment by HelgeBrands** [comment]
Hi Matt,

i found the problem with the crash. When you are using Qt5 QWT should be compile by Qt5!!!!

You have to install qwt-qt5* and qwt-qt5-devel* and change in the caQtDM_Env-File QWTINCLUDE=/usr/include/qt5/qwt

Then it works

Best regrads
                Helge

**Comment by newville** [comment]
@HelgeBrands With th caQtDM_Env file below, and adding `unix | ' in `caQtDM_Viewer/qtdefs.pri` does allow caQtDM to build.

But it still crashes immediately.

## caQtDM_Env:

```
#!/bin/bash

  if [ -z "$QTHOME" ];                then export   QTHOME=/usr/lib64;
  fi
  if [ -z "$QWTHOME" ];               then export   QWTHOME=/usr;
  fi
  if [ -z "$QWTINCLUDE" ];            then export   QWTINCLUDE=/usr/include/qt5/qwt;
  fi
  if [ -z "$QWTLIB" ];                then export   QWTLIB=${QWTHOME}/lib;
  fi
  if [ -z "$QWTVERSION" ];            then export   QWTVERSION=6.1;
  fi
  if [ -z "$EPICS_BASE" ];            then export   EPICS_BASE=/usr/local/epics/base;
  fi
  if [ -z "$EPICSINCLUDE" ];          then export   EPICSINCLUDE=${EPICS_BASE}/include;
  fi
  if [ -z "$EPICSLIB" ];              then  export  EPICSLIB=${EPICS_BASE}/lib/$EPICS_HOST_ARCH;
  fi
  if [ -z "$EPICS4LOCATION" ];         then  export  EPICS4LOCATION=/home/mezger/EPICS-CPP-4.6.0/
  fi
  if [ -z "$EPICSEXTENSIONS" ];     then  export  EPICSEXTENSIONS=/usr/local/epics/extensions;
  fi
  if [ -z "$QTCONTROLS_LIBS" ];       then export  QTCONTROLS_LIBS=`pwd`/caQtDM_Binaries;
  fi
  if [ -z "$CAQTDM_COLLECT" ];       then export  CAQTDM_COLLECT=`pwd`/caQtDM_Binaries;
  fi
  export  QTBASE=${QTCONTROLS_LIBS};

  if [ -z "$CAQTDM_CA_ARCHIVELIBS" ];       then export  CAQTDM_CA_ARCHIVELIBS=`pwd`/caQtDM_Binaries;
  fi
  if [ -z "$CAQTDM_LOGGING_ARCHIVELIBS" ];       then export  CAQTDM_LOGGING_ARCHIVELIBS=`pwd`/caQtDM_Binaries;
  fi

  if [ -z "$QTDM_LIBINSTALL" ];  then  export  QTDM_LIBINSTALL=$EPICSEXTENSIONS/lib/$EPICS_HOST_ARCH;
  fi
  if [ -z "$QTDM_BININSTALL" ];   then  export  QTDM_BININSTALL=$EPICSEXTENSIONS/bin/$EPICS_HOST_ARCH;
  fi

  if [ -z "$PYTHONVERSION" ];   then  export  PYTHONVERSION=2.7;
  fi
  if [ -z "$PYTHONINCLUDE" ];   then  export  PYTHONINCLUDE=/usr/include/python$PYTHONVERSION;
  fi
  if [ -z "$PYTHONLIB" ];   then  export  PYTHONLIB=/usr/lib/;
  fi

  if [ -z "$ZMQ" ];   then  export  ZMQ=/usr/local;
  fi
  if [ -z "$ZMQINC" ];   then  export  ZMQINC=$ZMQ/include;
  fi
  if [ -z "$ZMQLIB" ];   then  export  ZMQLIB=$ZMQ/lib;
  fi



  if [ -z "$TROLLTECH" ]; then
    echo
    echo ====== do not use psi trolltech directories
    echo
    if [ -z "$QTDM_RPATH" ];   then export  QTDM_RPATH=${QTDM_LIBINSTALL}:$TROLLTECH/binQt:${QTBASE};
    fi
  else
    echo
    echo ====== use psi trolltech directories
    echo
    if [ -z "$QTDM_RPATH" ];   then export  QTDM_RPATH=${QTDM_LIBINSTALL}:$TROLLTECH/binQt;
    fi
  fi

 if [ -z "$QTDM_RPATH" ];   then export  QTDM_RPATH=${QTDM_LIBINSTALL}:$TROLLTECH/binQt:${QTBASE};
 fi

echo =============================================================================================
echo in order to build this package you will eventually have to redefine following variables in
echo this file, they are taken from your environment if they exist, otherwise define them yourself:
echo
echo for building:
echo
echo QTHOME               now defined as ${QTHOME}               for locating Qt
echo QWTHOME              now defined as ${QWTHOME}              for locating qwt
echo QWTINCLUDE           now defined as ${QWTINCLUDE}           for locating the include files of qwt
echo QWTLIB               now defined as ${QWTLIB}               for locating the libraries of qwt
echo EPICS_BASE           now defined as ${EPICS_BASE}           for locating epics
echo EPICSINCLUDE         now defined as ${EPICSINCLUDE}         for locating epics include files
echo EPICSLIB             now defined as ${EPICSLIB}             for locating epics libraries
echo QTBASE               now defined as ${QTBASE}               for building the package locally, pointing to caQtDM_Binaries
echo QTDM_RPATH           now defined as ${QTDM_RPATH}           for runtime search path
echo
echo libraries for channel access archive and logging archive:
echo
echo CAQTDM_LOGGING_ARCHIVELIBS      now defined as ${CAQTDM_LOGGING_ARCHIVELIBS}   for logging archive rpc library
echo CAQTDM_CA_ARCHIVELIBS           now defined as ${CAQTDM_CA_ARCHIVELIBS}   for channel access archive library
echo
echo for python:
echo
echo PYTHONVERSION        now defined as ${PYTHONVERSION}        for locating python
echo PYTHONINCLUDE        now defined as ${PYTHONINCLUDE}        for locating python include files
echo PYTHONLIB            now defined as ${PYTHONLIB}            for locating python libraries
echo
echo for zmq:
echo
echo ZMQINC               now defined as ${ZMQINC}               for locating zmq include files
echo ZMQLIB               now defined as ${ZMQLIB}               for locating zmq libraries
echo
echo for install:
echo
echo EPICSEXTENSIONS      now defined as ${EPICSEXTENSIONS}      for locating epics extensions
echo QTDM_LIBINSTALL      now defined as ${QTDM_LIBINSTALL}      for libraries install
echo QTDM_BININSTALL      now defined as ${QTDM_BININSTALL}      for binaries install
echo ============================================================================================
echo

```

**Comment by HelgeBrands** [comment]
Hi Matt,

sorry I forgot the qwt-qt5 library.

In caqtdm.pri (line: 304) you need to change the linking too (-lqwt -> -lqwt-qt5)

caQtDM_QtControls {
        unix:!macx:!ios:!android {
                message("caQtDM_QtControls configuration : unix:!macx:!ios:!android")
                              OBJECTS_DIR = obj
                               DESTDIR = $$(CAQTDM_COLLECT)
                              INCLUDEPATH += $$(QWTINCLUDE)
                LIBS += -L$$(QWTLIB) -Wl,-rpath,$(QWTLIB) -lqwt-qt5
                }

Your qt4/qt5 problem belongs only to linux distributions.

Best regards
                Helge

**Comment by newville** [comment]
@HelgeBrands  OK, that gets further.  That builds a caQtDM that gives these messages (running in the caQtDM_Tests folder):


    rabbit:caQtDM_Tests>../caQtDM_Binaries/caQtDM 
    caQtDM -- file <caQtDM_stylesheet.qss> loaded as the default application stylesheet
    caQtDM -- viewer will disable monitors for hidden pages of QTabWidgets, in case of problems
          you may disable this by not defining IO_OPTIMIZED_FOR_TABWIDGETS in qtdefs.pri
    caQtDM -- files will not be downloaded from an url when not locally found, while     CAQTDM_URL_DISPLAY_PATH is not defined
   caQtDM -- Suspend epics connections for data in invisible tabs while CAQTDM_OPTIMIZE_EPICS3CONNECTIONS not set to TRUE

and the caQtDM menu is displayed with the caQtDM message buffer reading

    08-06-2018 12:19:22 Controlsystem plugins: attempt to load from /home/newville/Codes/caqtdm/caQtDM_Binaries/controlsystems
    08-06-2018 12:19:22 Epics3Plugin: epics version: EPICS 3.15.5
    08-06-2018 12:19:22 caQtDM will suspend epics connections for data in invisible tabs while CAQTDM_OPTIMIZE_EPICS3CONNECTIONS not set to TRUE 
    08-06-2018 12:19:22 Info: plugin archiveSF loaded
    08-06-2018 12:19:22 Info: plugin demo loaded
    08-06-2018 12:19:22 Info: plugin epics3 loaded
    08-06-2018 12:19:22 environment variable CAQTDM_TIMEOUT_HOURS could be set for quitting caQtDM automatically after some time


But opening any ui file, say `tests.ui` gives a segfault and 

    Gtk-Message: 12:15:10.342: GtkDialog mapped without a transient parent. This is discouraged.
    Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
    Segmentation fault (core dumped)


>  Your qt4/qt5 problem belongs only to linux distributions. 

The Issue here is labelled clearly with "Fedora 28".

Anyway, I feel like we're making progress.  Cheers!

**Comment by AntonMezger** [comment]
Hi Matt,

The first thing to verify is the presence of the ca widgets in the designer. If these are displayed then you have already made a progress. If not then the build of these plugins are already a problem

Being next week at argonne, I could eventually get a virtual system in order to verify and finalize the build

Best regards

Anton


Envoyé de mon iPhone

Le 8 juin 2018 à 12:21, Matt Newville <notifications@github.com<mailto:notifications@github.com>> a écrit :


@HelgeBrands<https://github.com/HelgeBrands> OK, that gets further. That builds a caQtDM that gives these messages (running in the caQtDM_Tests folder):

rabbit:caQtDM_Tests>../caQtDM_Binaries/caQtDM
caQtDM -- file <caQtDM_stylesheet.qss> loaded as the default application stylesheet
caQtDM -- viewer will disable monitors for hidden pages of QTabWidgets, in case of problems
      you may disable this by not defining IO_OPTIMIZED_FOR_TABWIDGETS in qtdefs.pri
caQtDM -- files will not be downloaded from an url when not locally found, while     CAQTDM_URL_DISPLAY_PATH is not defined


caQtDM -- Suspend epics connections for data in invisible tabs while CAQTDM_OPTIMIZE_EPICS3CONNECTIONS not set to TRUE

and the caQtDM menu is displayed with the caQtDM message buffer reading

08-06-2018 12:19:22 Controlsystem plugins: attempt to load from /home/newville/Codes/caqtdm/caQtDM_Binaries/controlsystems
08-06-2018 12:19:22 Epics3Plugin: epics version: EPICS 3.15.5
08-06-2018 12:19:22 caQtDM will suspend epics connections for data in invisible tabs while CAQTDM_OPTIMIZE_EPICS3CONNECTIONS not set to TRUE
08-06-2018 12:19:22 Info: plugin archiveSF loaded
08-06-2018 12:19:22 Info: plugin demo loaded
08-06-2018 12:19:22 Info: plugin epics3 loaded
08-06-2018 12:19:22 environment variable CAQTDM_TIMEOUT_HOURS could be set for quitting caQtDM automatically after some time


But opening any ui file, say tests.ui gives a segfault and

Gtk-Message: 12:15:10.342: GtkDialog mapped without a transient parent. This is discouraged.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Segmentation fault (core dumped)


Your qt4/qt5 problem belongs only to linux distributions.

The Issue here is labelled clearly with "Fedora 28".

Anyway, I feel like we're making progress. Cheers!

**Comment by newville** [comment]
On Fri, Jun 8, 2018 at 3:28 PM Anton Mezger <notifications@github.com>
wrote:

> Hi Matt,
>
> The first thing to verify is the presence of the ca widgets in the
> designer. If these are displayed then you have already made a progress. If
> not then the build of these plugins are already a problem
>

Yes, well running the ./qtdesigner script segfaults with
     ./qtdesigner: line 11: 11621 Segmentation fault      (core dumped)
designer -style plastique $*


> Being next week at argonne, I could eventually get a virtual system in
> order to verify and finalize the build
>
>
​OK. I'll be around all week too!

**Comment by AntonMezger** [comment]
the proble is solved, the main problem was mixing of Qt versions

**Comment by newville** [comment]
Thanks!

**Comment by newville** [comment]
I am again encountering errors when building the latest development version on Fedora 28.  
I have environmental variables set with

```
export QTHOME=/usr/
export QWTHOME=/home/include/qt5
export QWTINCLUDE=/usr/include/qt5/qwt
export QTBASE=/usr/lib64

export QWTLIB=/usr/lib64
export QWTLIBNAME=qwt-qt5
export QTDIR=$QTHOME
export QTINC=$QTHOME/include
export QMAKESPEC=linux-g++-64
export QWT_INCLUDE_PATH=$QWTINCLUDE

export CAQTDM_COLLECT=$HOME/local/lib
export QTDM_LIBINSTALL=$HOME/local/lib
export QTDM_RPATH=$HOME/local/lib

export EPICS_BASE=/usr/local/epics/base
export EPICSINCLUDE=$EPICS_BASE/include
export EPICS_HOST_ARCH=linux-x86_64
export EPICSLIB=$EPICS_BASE/lib/$EPICS_HOST_ARCH
export EPICSBIN=$EPICS_BASE/bin/$EPICS_HOST_ARCH

export PATH=$HOME/local/bin:/usr/local/bin:/usr/bin:/bin:$EPICSBIN:/usr/lib64/qt5/bin

export LD_LIBRARY_PATH=$EPICSLIB
export PYTHONVERSION=2.7
export PYTHONINCLUDE=/usr/include/python2.7
```

and the do `./caQtDM_BuildAll` which leads to an error finding a library when building some of the plugins:

```
make[3]: Entering directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins/archive/archiveSF'
/usr/bin/ld: cannot find -lcaQtDM_Lib
collect2: error: ld returned 1 exit status
rm -f libarchiveSF_plugin.so
make[2]: *** [Makefile:258: /home/newville/local/lib/controlsystems/libdemo_plugin.so] Error 1
make[2]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins/demo'
g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib64 -shared -o libarchiveSF_plugin.so obj/archiveSF_plugin.o obj/sfRetrieval.o obj/archiverCommon.o obj/moc_archiveSF_plugin.o obj/moc_sfRetrieval.o obj/moc_archiverCommon.o  -L/usr/X11R6/lib64 -L/home/newville/Codes/caqtdm/caQtDM_Binaries -Wl,-rpath,/home/newville/local/lib -lcaQtDM_Lib -lQt5UiTools -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread  
make[1]: *** [Makefile.csplugins:47: sub-demo-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcaQtDM_Lib
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:261: /home/newville/local/lib/controlsystems/libepics3_plugin.so] Error 1
make[2]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins/epics3'
make[1]: *** [Makefile.csplugins:72: sub-epics3-make_first] Error 2
/usr/bin/ld: cannot find -lcaQtDM_Lib
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:270: /home/newville/local/lib/controlsystems/libarchiveSF_plugin.so] Error 1
make[3]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins/archive/archiveSF'
make[2]: *** [Makefile:45: sub-archiveSF-make_first] Error 2
make[2]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins/archive'
make[1]: *** [Makefile.csplugins:97: sub-archive-make_first] Error 2
make[1]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_Lib/caQtDM_Plugins'
make: *** [Makefile:239: sub-caQtDM_Lib-caQtDM_Plugins-csplugins-pro-make_first] Error 2
rm -f libqtcontrols_graphics_plugin.so
g++ -m64 -Wl,-O1 -shared -o libqtcontrols_graphics_plugin.so obj/qtcontrols_graphics_plugin.o obj/qrc_qtcontrolsplugin.o obj/moc_qtcontrols_graphics_plugin.o  -L/usr/X11R6/lib64 -L/usr/lib64 -Wl,-rpath,/usr/lib64 -lqwt-qt5 -L/home/newville/Codes/caqtdm/caQtDM_Binaries -Wl,-rpath,/home/newville/local/lib -lqtcontrols -lQt5UiTools -lpthread -lQt5OpenGL -lQt5Designer -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL  
/usr/bin/ld: cannot find -lqtcontrols
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.qtcontrols_graphics:261: /home/newville/local/lib/designer/libqtcontrols_graphics_plugin.so] Error 1
make[1]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_QtControls/plugins'
make: *** [Makefile:162: sub-caQtDM_QtControls-plugins-qtcontrols_graphics-pro-make_first] Error 2
rm -f libqtcontrols_monitors_plugin.so
g++ -m64 -Wl,-O1 -shared -o libqtcontrols_monitors_plugin.so obj/qtcontrols_monitors_plugin.o obj/qrc_qtcontrolsplugin.o obj/moc_qtcontrols_monitors_plugin.o  -L/usr/X11R6/lib64 -L/usr/lib64 -Wl,-rpath,/usr/lib64 -lqwt-qt5 -L/home/newville/Codes/caqtdm/caQtDM_Binaries -Wl,-rpath,/home/newville/local/lib -lqtcontrols -lQt5UiTools -lpthread -lQt5OpenGL -lQt5Designer -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL  
/usr/bin/ld: cannot find -lqtcontrols
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.qtcontrols_monitors:261: /home/newville/local/lib/designer/libqtcontrols_monitors_plugin.so] Error 1
make[1]: Leaving directory '/home/newville/Codes/caqtdm/caQtDM_QtControls/plugins'
make: *** [Makefile:188: sub-caQtDM_QtControls-plugins-qtcontrols_monitors-pro-make_first] Error 2
```

Should I open a new Issue?

**Comment by newville** [comment]
Sorry for the noise, and an update.   If I change Environmental Variables to be

```
export QTHOME=/usr/
export QWTHOME=/home/include/qt5
export QWTINCLUDE=/usr/include/qt5/qwt
export QTBASE=/usr/lib64

export QWTLIB=/usr/lib64
export QWTLIBNAME=qwt-qt5
export QTDIR=$QTHOME
export QTINC=$QTHOME/include
export QMAKESPEC=linux-g++-64
export QWT_INCLUDE_PATH=$QWTINCLUDE

export CAQTDM_COLLECT=/usr/lib64
export QTDM_LIBINSTALL=/usr/lib64
export QTDM_RPATH=/usr/lib64

export EPICS_BASE=/usr/local/epics/base
export EPICSINCLUDE=$EPICS_BASE/include
export EPICS_HOST_ARCH=linux-x86_64
export EPICSLIB=$EPICS_BASE/lib/$EPICS_HOST_ARCH
export EPICSBIN=$EPICS_BASE/bin/$EPICS_HOST_ARCH

export PATH=$HOME/local/bin:/usr/local/bin:/usr/bin:/bin:$EPICSBIN:/usr/lib64/qt5/bin

export LD_LIBRARY_PATH=$EPICSLIB:$HOME/local/lib
export PYTHONVERSION=2.7
export PYTHONINCLUDE=/usr/include/python2.7
```

and build with `sudo ./caQtDM_BuildAll` then it does work (caQtDM runs and displays ui files, and the local bash script to run qtdesigner runs, with caQt plugins found).
